NXP-30654: fix random Chronicle test failures
Fix failure:

    expected:<[a key]> but was:<[Hi]>
    at org.nuxeo.runtime.stream.tests.TestStreamService.testStreamProcessor(TestStreamService.java:126)

due to TestStreamServiceDisabledProcessing running before.