NXP-31458: Fix CMIS ftests
The CMIS ftests rely on an old Python 2 library, `cmislib`, unmaintained for a while and without any working equivalent in Python 3.
As Python 2 is deprecated for a long time, there is no `python2` package available for Rocky Linux 9. The only way to have Python 2 in the Rocky Linux 9 builder image is to build it from sources.
Though the `openssl-devel` package is installed, the Python 2 compilation fails to build the `_ssl` module, with errors such as:
```
/Python-2.7.5/Modules/_ssl.c:610:35: error: invalid use of incomplete typedef 'X509_NAME_ENTRY' {aka 'struct X509_name_entry_st'}
```
This leads to the following error when trying to access `httplib.HTTPSConnection` in the `httplib2` library:
```
AttributeError: 'module' object has no attribute 'HTTPSConnection'
```
As a workaround, since we don't need HTTPS connection for the CMIS ftests, we simply delete the related code.